apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: devops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: image-registry.openshift-image-registry.svc:5000/devops/cargo-service:latest
          imagePullPolicy: Always
