apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-2
spec:
  selector:
    matchLabels:
      app: myapp-2
  replicas: 3
  template:
    metadata:
      labels:
        app: myapp-2
    spec:
      containers:
      - name: myapp-2
        image: default-route-openshift-image-registry.apps.stgocp.mwanitest.local/devops/poc-devops
        ports:
        - containerPort: 8080
