apiVersion: apps/v1
kind: Deployment
metadata:
  name: cargo
  namespace: devops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cargo
  template:
    metadata:
      labels:
        app: cargo
    spec:
      containers:
        - name: cargo
          image: image-registry.openshift-image-registry.svc:5000/devops/cargo-service:latest
          imagePullPolicy: Always
