apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frontend
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/devops/fe:latest1
        name: frontend
        securityContext:
          runAsUser: 1000680000
          runAsGroup: 1000680000
