apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-Hany
  namespace: devops
spec:
  replicas: 6
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: image-registry.openshift-image-registry.svc:5000/devops/poc-devops:latest
          imagePullPolicy: Always
