kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: frontend
  namespace: devops
spec:
  host: frontend-devops.apps.stgocp.mwanitest.local
  to:
    kind: Service
    name: frontend
    weight: 100
  port:
    targetPort: 5173
  tls:
    termination: edge
  wildcardPolicy: None
